from __future__ import annotations

HAS_TASK = "HAS_TASK"
HAS_EVIDENCE = "HAS_EVIDENCE"
HAS_CONTEXT_PACK = "HAS_CONTEXT_PACK"
HAS_PROPOSAL = "HAS_PROPOSAL"
HAS_APPROVAL = "HAS_APPROVAL"
HAS_EXECUTION = "HAS_EXECUTION"
ESCALATED_TO = "ESCALATED_TO"
LOCKED_BY = "LOCKED_BY"
